[versions]
guava = "33.5.0-jre"
gson = "2.13.2"
snakeyaml = "2.3"
jackson = "2.16.0"
mixin = "0.17.0+mixin.0.8.7"
mixin-extras = "0.5.0"
asm = "9.9.1"
paper-dev-bundle = "1.21.11-R0.1-SNAPSHOT"
userdev = "2.3.12"
run-paper = "3.0.2"
jspecify = "1.0.0"
junit = "6.0.0"
shadow = "9.2.2"

[libraries]
jbsdiff = { module = "io.sigpipe:jbsdiff", version = "1.0" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
jackson = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-toml", version.ref = "jackson"}
fabric-mixin = { module = "net.fabricmc:sponge-mixin", version.ref = "mixin" }
mixin-extras = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixin-extras" }
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-analysis = { module = "org.ow2.asm:asm-analysis", version.ref = "asm" }
asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
asm-tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm" }
asm-util = { module = "org.ow2.asm:asm-util", version.ref = "asm" }
cadix-at = { module = "org.cadixdev:at", version = "0.1.0-rc1" }
cadix-bombe = { module = "org.cadixdev:bombe", version = "0.3.4" }
cadix-bombe-asm = { module = "org.cadixdev:bombe-asm", version = "0.3.4" }
cadix-atlas = { module = "org.cadixdev:atlas", version = "0.2.1" }
userdev = { module = "io.canvasmc.weaver.userdev:io.canvasmc.weaver.userdev.gradle.plugin", version.ref = "userdev" }
run-paper = { module = "xyz.jpenilla.run-paper:xyz.jpenilla.run-paper.gradle.plugin", version.ref = "run-paper" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }

# for tests
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }

[bundles]
mixin = [ "fabric-mixin", "mixin-extras" ]
asm = [ "asm", "asm-analysis", "asm-commons", "asm-tree", "asm-util" ]

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
blossom = { id = "net.kyori.blossom", version = "2.2.0" }
spotless = { id = "com.diffplug.spotless", version = "8.1.0" }
plugin-publish = { id = "com.gradle.plugin-publish", version = "1.2.0" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.1.0" }
userdev = { id = "io.canvasmc.weaver.userdev", version.ref = "userdev" }
