[versions]
guava = "33.4.0-jre"
gson = "2.13.2"
snakeyaml = "2.3"
jackson = "2.16.0"
mixin = "0.17.0+mixin.0.8.7"
mixin-extras = "0.5.0"
asm = "9.9.1"
tinylog = "2.7.0"
paper-dev-bundle = "1.21.11-R0.1-SNAPSHOT"
shadow = "9.2.2"
userdev = "2.3.12-SNAPSHOT"
jspecify = "1.0.0"
junit = "6.0.0"
java = "21"

[libraries]
jbsdiff = { module = "io.sigpipe:jbsdiff", version = "1.0" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
jackson = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-toml", version.ref = "jackson"}
fabric-mixin = { module = "net.fabricmc:sponge-mixin", version.ref = "mixin" }
mixin-extras = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixin-extras" }
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-analysis = { module = "org.ow2.asm:asm-analysis", version.ref = "asm" }
asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
asm-tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm" }
asm-util = { module = "org.ow2.asm:asm-util", version.ref = "asm" }
tinylog-api = { module = "org.tinylog:tinylog-api", version.ref = "tinylog" }
tinylog-impl = { module = "org.tinylog:tinylog-impl", version.ref = "tinylog" }
userdev = { module = "io.canvasmc.weaver.userdev:io.canvasmc.weaver.userdev.gradle.plugin", version.ref = "userdev" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }

# for tests
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }

[bundles]
mixin = [ "fabric-mixin", "mixin-extras" ]
asm = [ "asm", "asm-analysis", "asm-commons", "asm-tree", "asm-util" ]
tinylog = [ "tinylog-api", "tinylog-impl" ]

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
blossom = { id = "net.kyori.blossom", version = "2.2.0" }
spotless = { id = "com.diffplug.spotless", version = "8.1.0" }
plugin-publish = { id = "com.gradle.plugin-publish", version = "1.2.0" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.1.0" }
userdev = { id = "io.canvasmc.weaver.userdev", version.ref = "userdev" }
